In [35]:
from google.colab import drive
drive.mount('/content/drive')

drivePath = '/content/drive/MyDrive/Colab Notebooks/'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
!nvidia-smi

Thu Jul  1 11:20:43 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.27       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [5]:
!pip uninstall torch
!pip install torch

Uninstalling torch-1.8.1+cu111:
  Would remove:
    /usr/local/lib/python3.7/dist-packages/torch-1.8.1+cu111.dist-info/*
    /usr/local/lib/python3.7/dist-packages/torch/*
Proceed (y/n)? y
  Successfully uninstalled torch-1.8.1+cu111
     |████████████████████████████████| 831.4MB 17kB/s 
ERROR: Operation cancelled by user


In [4]:
SEED = 1234

import torch
torch.manual_seed(SEED)
torch.backends.cudnn.deterministic = True

# Download dataset from official website

In [5]:
#@title Download CoNSeP
!rm -rf CoNSeP
!wget https://warwick.ac.uk/fac/cross_fac/tia/data/hovernet/consep.zip
!unzip /content/consep.zip > /dev/null
!rm -rf _*; rm /content/consep.zip

--2021-07-01 11:35:57--  https://warwick.ac.uk/fac/cross_fac/tia/data/hovernet/consep.zip
Resolving warwick.ac.uk (warwick.ac.uk)... 137.205.28.41
Connecting to warwick.ac.uk (warwick.ac.uk)|137.205.28.41|:443... connected.
HTTP request sent, awaiting response... 200 
Length: 153334740 (146M) [application/zip]
Saving to: ‘consep.zip’

consep.zip          100%[===================>] 146.23M  20.9MB/s    in 13s     

2021-07-01 11:36:11 (11.2 MB/s) - ‘consep.zip’ saved [153334740/153334740]



In [6]:
import os
import scipy.io
import numpy as np
from PIL import Image

In [7]:
#@title view labels and images
# mat = scipy.io.loadmat('/content/CoNSeP/Train/Labels/train_1.mat')

import matplotlib.pyplot as plt

# H = mat['inst_map']

# plt.imshow(H, interpolation='none')
# plt.show()

# H = mat['type_map']

# plt.imshow(H, interpolation='none')
# plt.show()

# image = np.array(Image.open('/content/CoNSeP/Train/Images/train_24.png'))
# H = image[:,:,3]

# plt.imshow(H, interpolation='none')
# plt.show()

# Data loaders

In [8]:
import torch.nn as nn

class ConsepSimplePadDataset(torch.utils.data.Dataset):
  def __init__(self, train = False, test = False):
        self.directory = 'CoNSeP/Train' if train else 'CoNSeP/Test'
        self.setname = 'train' if train else 'test'
        assert train != test

  def __len__(self):
        return len(os.listdir(os.path.join(self.directory, 'Images')))

  def __getitem__(self, index):
        # Load data and get label
        image = np.array(Image.open(os.path.join(self.directory, 'Images', self.setname + f'_{index + 1}.png')))[:,:,:3]
        image = torch.from_numpy(np.transpose(image, (2, 0, 1))) / 255

        labels = scipy.io.loadmat(os.path.join(self.directory, 'Labels', self.setname + f'_{index + 1}.mat'))
        label_inst = torch.from_numpy(labels['inst_map']).long()
        label_type = torch.from_numpy(labels['type_map']).long()

        m = nn.ZeroPad2d(12)

        return m(image), m(label_inst), m(label_type)

In [9]:
# CUDA for PyTorch
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Parameters
params = {'batch_size': 1,
          'shuffle': True,
          'num_workers': 0}

# Generators
training_set = ConsepSimplePadDataset(train = True)
validation_len = int(len(training_set) * 0.3)

training_set, validation_set = torch.utils.data.random_split(training_set, [len(training_set) - validation_len, validation_len])
training_generator = torch.utils.data.DataLoader(training_set, **params)
validation_generator = torch.utils.data.DataLoader(validation_set, **params)

test_set = ConsepSimplePadDataset(test = True)
test_generator = torch.utils.data.DataLoader(test_set, **params)

In [10]:
n_type = 8
ratio_type = torch.ones(n_type)
ratio_inst = torch.ones(2)
for _, local_labels_inst, local_labels_type in training_generator:
    for i in range(n_type):
        ratio_type[i] += torch.sum(local_labels_type == i)
    ratio_inst[0] += torch.sum(local_labels_inst == 0)
    ratio_inst[1] += torch.sum(local_labels_inst > 0)

# Model

In [1]:
#@title clone UNetPlusPlus
!pip install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio==0.8.1 -f https://download.pytorch.org/whl/lts/1.8/torch_lts.html >/dev/null
!pip install torchtext==0.9.1 >/dev/null
!pip install segmentation-models-pytorch >/dev/null
import segmentation_models_pytorch

tcmalloc: large alloc 1982177280 bytes == 0x55c085b26000 @  0x7f632be711e7 0x55c082e90e68 0x55c082e5b637 0x55c082fda605 0x55c082f740b8 0x55c082e5ef02 0x55c082f3cd1e 0x55c082e5eb59 0x55c082f4ffed 0x55c082ed2988 0x55c082e6030a 0x55c082ece60e 0x55c082e6030a 0x55c082ece60e 0x55c082ecd7ad 0x55c082e60c9f 0x55c082e60ea1 0x55c082ecfbb5 0x55c082ecd4ae 0x55c082e60c9f 0x55c082e60ea1 0x55c082ecfbb5 0x55c082ecd4ae 0x55c082e60c9f 0x55c082e60ea1 0x55c082ecfbb5 0x55c082ecd7ad 0x55c082e60c9f 0x55c082e60ea1 0x55c082ecfbb5 0x55c082ecd4ae
tcmalloc: large alloc 1982177280 bytes == 0x55c0fbd80000 @  0x7f632be711e7 0x55c082e90e68 0x55c082e5b637 0x55c082f717e7 0x55c082e5ec7c 0x55c082f4ffed 0x55c082ed2988 0x55c082e6030a 0x55c082ece60e 0x55c082e6030a 0x55c082ece60e 0x55c082ecd7ad 0x55c082e60c9f 0x55c082e60ea1 0x55c082ecfbb5 0x55c082ecd4ae 0x55c082e60c9f 0x55c082e60ea1 0x55c082ecfbb5 0x55c082ecd4ae 0x55c082e60c9f 0x55c082e60ea1 0x55c082ecfbb5 0x55c082ecd7ad 0x55c082e60c9f 0x55c082e60ea1 0x55c082ecfbb5 0x55c082ec

In [11]:
model = segmentation_models_pytorch.UnetPlusPlus(encoder_name='resnet34', encoder_depth=5, encoder_weights='imagenet', decoder_use_batchnorm=True, decoder_channels=(256, 128, 64, 32, 16), decoder_attention_type=None, in_channels=3, classes=n_type, activation=None, aux_params=None)
model = model.to(device)

Downloading: "https://download.pytorch.org/models/resnet34-333f7ec4.pth" to /root/.cache/torch/hub/checkpoints/resnet34-333f7ec4.pth


In [12]:
def count_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)

print(f'The model has {count_parameters(model):,} trainable parameters')

The model has 26,079,624 trainable parameters


# Training

In [13]:
from torch import optim

optimizer = optim.RMSprop(model.parameters(), lr=1e-3, weight_decay=1e-8, momentum=0.9)

if n_type > 1:
    criterion = nn.CrossEntropyLoss(weight = 1 / torch.log(ratio_type).to(device))
else:
    criterion = nn.CrossEntropyLoss(weight = 1 / torch.log(ratio_inst).to(device))

In [14]:
def categorical_accuracy(preds, y):
    """
    Returns accuracy per batch, i.e. if you get 8/10 right, this returns 0.8, NOT 8
    """
    top_pred = preds.argmax(1, keepdim = True)
    correct = top_pred.eq(y.view_as(top_pred)).float().mean()
    acc = correct
    return acc

In [15]:
def binary_metric(preds, y, n_classes=8):
    rounded_preds = preds.argmax(1)
    scores = []
    t = rounded_preds == y
    for i in range(n_classes):
        p = rounded_preds == i
        tp = torch.sum(torch.logical_and(t, p).float(), dim = 1)
        fp = torch.sum(torch.logical_and(torch.logical_not(t), p).float(), dim = 1)
        fn = torch.sum(torch.logical_and(torch.logical_and(torch.logical_not(t), torch.logical_not(p)), y == i).float(), dim = 1)

        recall = tp / (tp + fn + 1e-10)
        prec = tp / (tp + fp + 1e-10)
        f1 = 2 * tp / (2 * tp + fp + fn + 1e-10)
        f2 = 5 * tp / (5 * tp + 4 * fn + fp + 1e-10)
        scores.append([recall.mean(), prec.mean(), f1.mean(), f2.mean()])
    
    return torch.tensor(scores)

In [16]:
from tqdm.notebook import tqdm

def train(model, iterator, optimizer, criterion):
    
    epoch_loss = 0
    epoch_acc = 0
    statistics = []

    model.train()

    for local_batch, local_labels_inst, local_labels_type in tqdm(iterator):

        # Transfer to GPU
        local_batch, local_labels_inst, local_labels_type = local_batch.to(device), local_labels_inst.to(device), local_labels_type.to(device)
        
        optimizer.zero_grad()
     
        type_pred = model(local_batch)
        
        loss = criterion(type_pred, local_labels_type)
        
        acc = categorical_accuracy(type_pred, local_labels_type)

        statistics.append(binary_metric(type_pred, local_labels_type))
        
        loss.backward()
        
        optimizer.step()
        
        epoch_loss += loss.item()
        epoch_acc += acc.item()
        
    return epoch_loss / len(iterator), epoch_acc / len(iterator), sum(statistics) / len(statistics)

In [17]:
def evaluate(model, iterator, criterion, demo = False):
    
    epoch_loss = 0
    epoch_acc = 0
    statistics = []

    model.eval()

    with torch.no_grad():

        for local_batch, local_labels_inst, local_labels_type in tqdm(iterator):

            # Transfer to GPU
            local_batch, local_labels_inst, local_labels_type = local_batch.to(device), local_labels_inst.to(device), local_labels_type.to(device)

            type_pred = model(local_batch)
        
            loss = criterion(type_pred, local_labels_type)
            
            acc = categorical_accuracy(type_pred, local_labels_type)

            statistics.append(binary_metric(type_pred, local_labels_type))

            epoch_loss += loss.item()
            epoch_acc += acc.item()

            #demo
            if demo:
                truth = local_labels_type.squeeze(0).cpu().numpy()
                plt.imshow(np.concatenate((type_pred.argmax(1).squeeze(0).cpu().numpy(), truth), axis = 1), interpolation='none')
                plt.show()
        
    return epoch_loss / len(iterator), epoch_acc / len(iterator), sum(statistics) / len(statistics)

In [44]:
def quality_metric(preds, y, n_classes=8):
  
    rounded_preds = preds.argmax(1)
    scores = []
    t = rounded_preds == y
    for i in range(n_classes):
        p = rounded_preds == i
        l = y == i
        tp = torch.sum(torch.logical_and(t, p).float(), dim = 1)
        fp = torch.sum(torch.logical_and(torch.logical_not(t), p).float(), dim = 1)
        fn = torch.sum(torch.logical_and(torch.logical_and(torch.logical_not(t), torch.logical_not(p)), y == i).float(), dim = 1)
        
        f1 = 2 * tp / (2 * tp + fp + fn + 1e-10)

        intersection = (l & p).float().sum((1, 2)) 
        union = (l | p).float().sum((1, 2)) 
        
        iou = (intersection + 1e-10) / (union + 1e-10)

        scores.append([f1.mean(), iou, f1.mean()*iou])
    
    return torch.tensor(scores)

def AJI(preds, y, n_classes=8):
    rounded_preds = preds.argmax(1)
    total_intersection = 0
    total_union = 0
    for i in range(1, n_classes):
        p = rounded_preds == i
        l = y == i

        intersection = (l & p).float().sum((1, 2)) 
        union = (l | p).float().sum((1, 2)) 
        
        total_intersection += intersection
        total_union += union
    
    return (total_intersection + 1e-10) / (total_union + 1e-10)

def DICE_2(preds, y, n_classes=8):
    rounded_preds = preds.argmax(1)
    p = rounded_preds != 0
    l = y != 0
    total_intersection = 0
    for i in range(1, n_classes):
      m1 = rounded_preds == i
      m2 = y == i
      intersection = (m1 & m2).float().sum((1, 2))
      total_intersection += intersection 
    sumOfpl = l.float().sum((1, 2)) + p.float().sum((1, 2)) 
    DICE2 = 2* (total_intersection + 1e-10) / (sumOfpl + 1e-10)
    
    return DICE2

def classification_eval(preds, y):

    rounded_preds = preds.argmax(1)
    TPd = rounded_preds & y
    t = rounded_preds == y
    Ac = torch.logical_and(TPd, t).float().sum((1, 2))
    Bc = torch.logical_and(TPd, torch.logical_not(t)).float().sum((1, 2))
    incorrectDetection = torch.logical_xor(rounded_preds, y).float().sum((1, 2))
    
    Fc = (2*Ac+1e-10)/(2*(Ac+Bc)+incorrectDetection+1e-10)

    return Fc

In [41]:
def new_evaluate(model, iterator, criterion):
    
    epoch_loss = 0
    epoch_acc = 0
    # segmentation_scores = []
    DICE2_list = []
    AJI_list = []
    classification_scores = []
    model.eval()

    with torch.no_grad():

        for local_batch, local_labels_inst, local_labels_type in tqdm(iterator):

            # Transfer to GPU
            local_batch, local_labels_inst, local_labels_type = local_batch.to(device), local_labels_inst.to(device), local_labels_type.to(device)

            type_pred = model(local_batch)

            loss = criterion(type_pred, local_labels_type)
            
            acc = categorical_accuracy(type_pred, local_labels_type)

            epoch_loss += loss.item()
            epoch_acc += acc.item()


            DICE2_list.append(DICE_2(type_pred, local_labels_type))
            AJI_list.append(AJI(type_pred, local_labels_type))
            # segmentation_scores.append(quality_metric(type_pred, local_labels_type))
            classification_scores.append(classification_eval(type_pred, local_labels_type))

    return epoch_loss / len(iterator), epoch_acc / len(iterator), sum(DICE2_list) / len(DICE2_list), sum(AJI_list) / len(AJI_list), sum(classification_scores) / len(classification_scores)






In [42]:
import time

def epoch_time(start_time, end_time):
    elapsed_time = end_time - start_time
    elapsed_mins = int(elapsed_time / 60)
    elapsed_secs = int(elapsed_time - (elapsed_mins * 60))
    return elapsed_mins, elapsed_secs

In [45]:
N_EPOCHS = 50

best_valid_loss = float('inf')

for epoch in range(N_EPOCHS):

    start_time = time.time()

    train_loss, train_acc, train_stats = train(model, training_generator, optimizer, criterion)
    valid_loss, valid_acc, valid_DICE2, valid_AJI, valid_classification_score = new_evaluate(model, validation_generator, criterion)

    end_time = time.time()

    epoch_mins, epoch_secs = epoch_time(start_time, end_time)

    if valid_loss < best_valid_loss:
        best_valid_loss = valid_loss
        torch.save(model.state_dict(), drivePath + 'unetplusplus.pt')

    print(f'Epoch: {epoch+1:02} | Epoch Time: {epoch_mins}m {epoch_secs}s')
    print(f'\tTrain Loss: {train_loss:.3f} | Train Acc: {train_acc*100:.2f}%')
    print(f'\t Val. Loss: {valid_loss:.3f} |  Val. Acc: {valid_acc*100:.2f}%')
    print('train metrics R, P, F1, F2')
    print((train_stats * 1e4).long())
    print('valid metrics DICE2, AJI')
    print((valid_DICE2 * 1e4).long(), (valid_AJI * 1e4).long())
    print('valid classification score: ', valid_classification_score)


Epoch: 01 | Epoch Time: 0m 19s
	Train Loss: 0.358 | Train Acc: 88.35%
	 Val. Loss: 0.372 |  Val. Acc: 90.79%
train metrics R, P, F1, F2
tensor([[9432, 9449, 9430, 9428],
        [   0,    0,    0,    0],
        [1341, 2115, 1468, 1361],
        [   0,    0,    0,    0],
        [3280, 3214, 3177, 3220],
        [2315, 2849, 2293, 2245],
        [1301, 1351, 1270, 1272],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([2493], device='cuda:0') tensor([1648], device='cuda:0')
valid classification score:  tensor([0.2935], device='cuda:0')



Epoch: 02 | Epoch Time: 0m 19s
	Train Loss: 0.359 | Train Acc: 88.43%
	 Val. Loss: 0.351 |  Val. Acc: 88.92%
train metrics R, P, F1, F2
tensor([[9555, 9339, 9435, 9504],
        [   0,    0,    0,    0],
        [1496, 2114, 1542, 1478],
        [   0,    0,    0,    0],
        [3177, 3284, 3150, 3148],
        [1532, 2152, 1503, 1478],
        [1198, 1141, 1030, 1087],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([2089], device='cuda:0') tensor([1274], device='cuda:0')
valid classification score:  tensor([0.2884], device='cuda:0')



Epoch: 03 | Epoch Time: 0m 19s
	Train Loss: 0.347 | Train Acc: 88.69%
	 Val. Loss: 0.383 |  Val. Acc: 89.10%
train metrics R, P, F1, F2
tensor([[9434, 9456, 9434, 9431],
        [   0,    0,    0,    0],
        [1489, 2168, 1597, 1497],
        [   0,    0,    0,    0],
        [3447, 3228, 3289, 3370],
        [2397, 3113, 2361, 2318],
        [1139, 1385, 1154, 1127],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([2562], device='cuda:0') tensor([1653], device='cuda:0')
valid classification score:  tensor([0.3053], device='cuda:0')



Epoch: 04 | Epoch Time: 0m 19s
	Train Loss: 0.407 | Train Acc: 87.73%
	 Val. Loss: 0.745 |  Val. Acc: 77.11%
train metrics R, P, F1, F2
tensor([[9497, 9343, 9402, 9454],
        [   0,    0,    0,    0],
        [1313, 2000, 1384, 1310],
        [   0,    0,    0,    0],
        [3088, 3354, 3119, 3080],
        [1951, 2912, 2081, 1954],
        [1328,  847,  970, 1111],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([766], device='cuda:0') tensor([485], device='cuda:0')
valid classification score:  tensor([0.1032], device='cuda:0')



Epoch: 05 | Epoch Time: 0m 19s
	Train Loss: 0.358 | Train Acc: 88.48%
	 Val. Loss: 0.502 |  Val. Acc: 84.46%
train metrics R, P, F1, F2
tensor([[9403, 9480, 9431, 9412],
        [   0,    0,    0,    0],
        [1791, 2250, 1776, 1741],
        [   0,    0,    0,    0],
        [3453, 3129, 3212, 3333],
        [2257, 2746, 2212, 2178],
        [1064, 1220, 1034, 1035],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([340], device='cuda:0') tensor([174], device='cuda:0')
valid classification score:  tensor([0.0602], device='cuda:0')



Epoch: 06 | Epoch Time: 0m 19s
	Train Loss: 0.388 | Train Acc: 88.05%
	 Val. Loss: 0.332 |  Val. Acc: 90.39%
train metrics R, P, F1, F2
tensor([[9465, 9426, 9436, 9451],
        [   0,    0,    0,    0],
        [ 938, 1795, 1116,  989],
        [   0,    0,    0,    0],
        [3271, 3195, 3150, 3200],
        [2209, 2955, 2209, 2135],
        [1110, 1056, 1039, 1064],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([2416], device='cuda:0') tensor([1544], device='cuda:0')
valid classification score:  tensor([0.3102], device='cuda:0')



Epoch: 07 | Epoch Time: 0m 19s
	Train Loss: 0.349 | Train Acc: 88.83%
	 Val. Loss: 0.470 |  Val. Acc: 86.97%
train metrics R, P, F1, F2
tensor([[9511, 9415, 9453, 9485],
        [   0,    0,    0,    0],
        [2051, 2041, 1802, 1882],
        [   0,    0,    0,    0],
        [3261, 3268, 3187, 3212],
        [1983, 3095, 2181, 2016],
        [1175, 1431, 1169, 1151],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([1554], device='cuda:0') tensor([933], device='cuda:0')
valid classification score:  tensor([0.2122], device='cuda:0')



Epoch: 08 | Epoch Time: 0m 19s
	Train Loss: 0.375 | Train Acc: 87.76%
	 Val. Loss: 0.388 |  Val. Acc: 90.14%
train metrics R, P, F1, F2
tensor([[9408, 9386, 9384, 9395],
        [   0,    0,    0,    0],
        [1063, 1939, 1203, 1092],
        [   0,    0,    0,    0],
        [3130, 3208, 3069, 3087],
        [2298, 2794, 2289, 2246],
        [1425, 1203, 1233, 1321],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([2333], device='cuda:0') tensor([1479], device='cuda:0')
valid classification score:  tensor([0.2806], device='cuda:0')



Epoch: 09 | Epoch Time: 0m 19s
	Train Loss: 0.351 | Train Acc: 88.47%
	 Val. Loss: 0.460 |  Val. Acc: 90.36%
train metrics R, P, F1, F2
tensor([[9474, 9421, 9438, 9457],
        [   0,    0,    0,    0],
        [1640, 2128, 1661, 1612],
        [   0,    0,    0,    0],
        [3223, 3220, 3137, 3169],
        [2071, 2857, 2015, 1993],
        [1175, 1411, 1139, 1136],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([1699], device='cuda:0') tensor([1047], device='cuda:0')
valid classification score:  tensor([0.2133], device='cuda:0')



Epoch: 10 | Epoch Time: 0m 19s
	Train Loss: 0.340 | Train Acc: 89.25%
	 Val. Loss: 0.328 |  Val. Acc: 89.81%
train metrics R, P, F1, F2
tensor([[9515, 9406, 9449, 9486],
        [   0,    0,    0,    0],
        [1887, 2266, 1866, 1835],
        [   0,    0,    0,    0],
        [3227, 3309, 3188, 3195],
        [2497, 3155, 2560, 2476],
        [1194, 1412, 1221, 1188],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([2581], device='cuda:0') tensor([1692], device='cuda:0')
valid classification score:  tensor([0.3172], device='cuda:0')



Epoch: 11 | Epoch Time: 0m 19s
	Train Loss: 0.334 | Train Acc: 88.86%
	 Val. Loss: 0.498 |  Val. Acc: 91.08%
train metrics R, P, F1, F2
tensor([[9474, 9455, 9455, 9464],
        [   0,    0,    0,    0],
        [2012, 2273, 1979, 1963],
        [   0,    0,    0,    0],
        [3209, 3328, 3174, 3176],
        [2368, 2833, 2309, 2294],
        [1371, 1348, 1260, 1291],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([1671], device='cuda:0') tensor([1108], device='cuda:0')
valid classification score:  tensor([0.1985], device='cuda:0')



Epoch: 12 | Epoch Time: 0m 19s
	Train Loss: 0.331 | Train Acc: 89.26%
	 Val. Loss: 0.325 |  Val. Acc: 90.59%
train metrics R, P, F1, F2
tensor([[9467, 9453, 9450, 9458],
        [   0,    3,    0,    0],
        [1658, 2291, 1715, 1644],
        [   0,    0,    0,    0],
        [3443, 3281, 3287, 3358],
        [2809, 3064, 2682, 2696],
        [1305, 1243, 1206, 1244],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([2549], device='cuda:0') tensor([1702], device='cuda:0')
valid classification score:  tensor([0.3105], device='cuda:0')



Epoch: 13 | Epoch Time: 0m 19s
	Train Loss: 0.330 | Train Acc: 89.40%
	 Val. Loss: 0.385 |  Val. Acc: 90.88%
train metrics R, P, F1, F2
tensor([[9475, 9467, 9462, 9468],
        [   0,    0,    0,    0],
        [1732, 2182, 1779, 1721],
        [   0,    0,    0,    0],
        [3432, 3267, 3306, 3369],
        [2428, 3308, 2499, 2404],
        [1512, 1326, 1346, 1419],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([2717], device='cuda:0') tensor([1801], device='cuda:0')
valid classification score:  tensor([0.3130], device='cuda:0')



Epoch: 14 | Epoch Time: 0m 19s
	Train Loss: 0.332 | Train Acc: 89.49%
	 Val. Loss: 0.459 |  Val. Acc: 86.72%
train metrics R, P, F1, F2
tensor([[9544, 9412, 9470, 9512],
        [   0,    0,    0,    0],
        [1864, 2002, 1753, 1765],
        [   0,    0,    0,    0],
        [3317, 3317, 3251, 3274],
        [2487, 3366, 2592, 2473],
        [1391, 1371, 1293, 1322],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([974], device='cuda:0') tensor([522], device='cuda:0')
valid classification score:  tensor([0.1504], device='cuda:0')



Epoch: 15 | Epoch Time: 0m 19s
	Train Loss: 0.331 | Train Acc: 89.50%
	 Val. Loss: 0.338 |  Val. Acc: 89.16%
train metrics R, P, F1, F2
tensor([[9468, 9490, 9472, 9468],
        [   0,    0,    0,    0],
        [1821, 2277, 1865, 1803],
        [   0,    0,    0,    0],
        [3495, 3287, 3330, 3413],
        [2642, 3359, 2642, 2587],
        [1138, 1330, 1117, 1108],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([2578], device='cuda:0') tensor([1669], device='cuda:0')
valid classification score:  tensor([0.3181], device='cuda:0')



Epoch: 16 | Epoch Time: 0m 19s
	Train Loss: 0.352 | Train Acc: 89.09%
	 Val. Loss: 0.342 |  Val. Acc: 91.88%
train metrics R, P, F1, F2
tensor([[9497, 9457, 9468, 9483],
        [   0,    3,    0,    0],
        [1986, 2193, 1905, 1909],
        [   0,    0,    0,    0],
        [3180, 3042, 3035, 3103],
        [2464, 2921, 2438, 2408],
        [1381, 1253, 1160, 1259],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([2306], device='cuda:0') tensor([1548], device='cuda:0')
valid classification score:  tensor([0.2611], device='cuda:0')



Epoch: 17 | Epoch Time: 0m 19s
	Train Loss: 0.338 | Train Acc: 89.49%
	 Val. Loss: 0.317 |  Val. Acc: 91.29%
train metrics R, P, F1, F2
tensor([[9536, 9432, 9475, 9510],
        [   6,   23,    9,    7],
        [1964, 2277, 1917, 1906],
        [   0,    0,    0,    0],
        [3344, 3337, 3267, 3294],
        [2722, 3437, 2797, 2700],
        [ 995, 1199,  979,  976],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([2643], device='cuda:0') tensor([1748], device='cuda:0')
valid classification score:  tensor([0.3190], device='cuda:0')



Epoch: 18 | Epoch Time: 0m 19s
	Train Loss: 0.321 | Train Acc: 89.36%
	 Val. Loss: 0.313 |  Val. Acc: 90.39%
train metrics R, P, F1, F2
tensor([[9470, 9472, 9462, 9464],
        [  38,   93,   47,   40],
        [1861, 2259, 1838, 1809],
        [   0,    0,    0,    0],
        [3422, 3334, 3315, 3362],
        [2612, 3486, 2735, 2615],
        [1475, 1211, 1267, 1362],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([2796], device='cuda:0') tensor([1906], device='cuda:0')
valid classification score:  tensor([0.3329], device='cuda:0')



Epoch: 19 | Epoch Time: 0m 19s
	Train Loss: 0.310 | Train Acc: 89.88%
	 Val. Loss: 0.590 |  Val. Acc: 89.30%
train metrics R, P, F1, F2
tensor([[9511, 9468, 9482, 9497],
        [   9,   25,   12,   10],
        [2222, 2289, 2091, 2123],
        [   0,    0,    0,    0],
        [3447, 3396, 3374, 3406],
        [2757, 3357, 2792, 2725],
        [1282, 1372, 1288, 1275],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([1200], device='cuda:0') tensor([711], device='cuda:0')
valid classification score:  tensor([0.1689], device='cuda:0')



Epoch: 20 | Epoch Time: 0m 19s
	Train Loss: 0.328 | Train Acc: 88.89%
	 Val. Loss: 0.341 |  Val. Acc: 91.77%
train metrics R, P, F1, F2
tensor([[9470, 9453, 9449, 9459],
        [  54,  124,   66,   58],
        [1484, 2069, 1533, 1461],
        [   0,    0,    0,    0],
        [3216, 3398, 3187, 3181],
        [2681, 3127, 2560, 2557],
        [1367, 1136, 1151, 1240],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([2402], device='cuda:0') tensor([1600], device='cuda:0')
valid classification score:  tensor([0.2903], device='cuda:0')



Epoch: 21 | Epoch Time: 0m 19s
	Train Loss: 0.328 | Train Acc: 89.16%
	 Val. Loss: 0.333 |  Val. Acc: 90.63%
train metrics R, P, F1, F2
tensor([[9505, 9411, 9442, 9476],
        [  13,   16,   13,   13],
        [2211, 2150, 2008, 2076],
        [   0,    0,    0,    0],
        [3324, 3361, 3236, 3265],
        [2317, 3400, 2467, 2320],
        [1289, 1368, 1271, 1270],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([2410], device='cuda:0') tensor([1588], device='cuda:0')
valid classification score:  tensor([0.2960], device='cuda:0')



Epoch: 22 | Epoch Time: 0m 19s
	Train Loss: 0.310 | Train Acc: 89.30%
	 Val. Loss: 0.368 |  Val. Acc: 88.97%
train metrics R, P, F1, F2
tensor([[9420, 9501, 9445, 9427],
        [   7,   11,    8,    7],
        [2198, 2360, 2099, 2113],
        [   0,    0,    0,    0],
        [3453, 3337, 3293, 3362],
        [2996, 3571, 3008, 2949],
        [1313, 1476, 1338, 1313],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([1956], device='cuda:0') tensor([1312], device='cuda:0')
valid classification score:  tensor([0.2347], device='cuda:0')



Epoch: 23 | Epoch Time: 0m 19s
	Train Loss: 0.311 | Train Acc: 90.16%
	 Val. Loss: 0.494 |  Val. Acc: 83.19%
train metrics R, P, F1, F2
tensor([[9522, 9486, 9498, 9511],
        [  46,  114,   58,   50],
        [1869, 2374, 1941, 1870],
        [   0,    0,    0,    0],
        [3525, 3384, 3397, 3458],
        [2729, 3603, 2859, 2743],
        [1493, 1311, 1359, 1424],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([1415], device='cuda:0') tensor([927], device='cuda:0')
valid classification score:  tensor([0.1678], device='cuda:0')



Epoch: 24 | Epoch Time: 0m 19s
	Train Loss: 0.300 | Train Acc: 90.14%
	 Val. Loss: 0.524 |  Val. Acc: 84.86%
train metrics R, P, F1, F2
tensor([[9540, 9471, 9500, 9522],
        [  14,   49,   19,   15],
        [2442, 2299, 2225, 2306],
        [   0,    0,    0,    0],
        [3336, 3484, 3362, 3335],
        [3023, 3639, 3092, 3007],
        [1402, 1405, 1324, 1343],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([1331], device='cuda:0') tensor([861], device='cuda:0')
valid classification score:  tensor([0.1631], device='cuda:0')



Epoch: 25 | Epoch Time: 0m 19s
	Train Loss: 0.302 | Train Acc: 90.05%
	 Val. Loss: 0.359 |  Val. Acc: 90.52%
train metrics R, P, F1, F2
tensor([[9506, 9482, 9483, 9494],
        [  75,  161,   92,   80],
        [2149, 2263, 2058, 2072],
        [   0,    0,    0,    0],
        [3480, 3407, 3367, 3415],
        [3011, 3556, 2987, 2947],
        [1464, 1422, 1402, 1428],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([2337], device='cuda:0') tensor([1494], device='cuda:0')
valid classification score:  tensor([0.2833], device='cuda:0')



Epoch: 26 | Epoch Time: 0m 19s
	Train Loss: 0.296 | Train Acc: 89.99%
	 Val. Loss: 0.332 |  Val. Acc: 92.05%
train metrics R, P, F1, F2
tensor([[9506, 9490, 9488, 9496],
        [  82,  150,   95,   86],
        [2102, 2317, 2040, 2039],
        [   0,    0,    0,    0],
        [3466, 3428, 3377, 3411],
        [2964, 3583, 3049, 2960],
        [1524, 1423, 1426, 1468],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([2749], device='cuda:0') tensor([1827], device='cuda:0')
valid classification score:  tensor([0.3264], device='cuda:0')



Epoch: 27 | Epoch Time: 0m 19s
	Train Loss: 0.355 | Train Acc: 88.89%
	 Val. Loss: 0.483 |  Val. Acc: 87.45%
train metrics R, P, F1, F2
tensor([[9440, 9520, 9469, 9449],
        [ 152,  234,  166,  155],
        [2415, 2199, 2108, 2209],
        [   0,    0,    0,    0],
        [3380, 3019, 3141, 3264],
        [2200, 2952, 2269, 2185],
        [ 812,  606,  664,  732],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([1415], device='cuda:0') tensor([853], device='cuda:0')
valid classification score:  tensor([0.1936], device='cuda:0')



Epoch: 28 | Epoch Time: 0m 19s
	Train Loss: 0.319 | Train Acc: 89.68%
	 Val. Loss: 0.351 |  Val. Acc: 91.45%
train metrics R, P, F1, F2
tensor([[9543, 9462, 9496, 9523],
        [ 110,  233,  131,  115],
        [1931, 2341, 1916, 1886],
        [   0,    0,    0,    0],
        [3350, 3493, 3379, 3352],
        [3532, 3498, 3254, 3338],
        [ 363,  506,  406,  377],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([2436], device='cuda:0') tensor([1612], device='cuda:0')
valid classification score:  tensor([0.3009], device='cuda:0')



Epoch: 29 | Epoch Time: 0m 19s
	Train Loss: 0.295 | Train Acc: 90.14%
	 Val. Loss: 0.318 |  Val. Acc: 91.34%
train metrics R, P, F1, F2
tensor([[9492, 9528, 9503, 9495],
        [ 122,  203,  140,  127],
        [2076, 2301, 2008, 2006],
        [   0,    0,    0,    0],
        [3524, 3421, 3425, 3472],
        [2719, 3292, 2774, 2706],
        [1491, 1288, 1333, 1409],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([2912], device='cuda:0') tensor([1951], device='cuda:0')
valid classification score:  tensor([0.3537], device='cuda:0')



Epoch: 30 | Epoch Time: 0m 19s
	Train Loss: 0.309 | Train Acc: 89.96%
	 Val. Loss: 0.385 |  Val. Acc: 90.72%
train metrics R, P, F1, F2
tensor([[9482, 9538, 9503, 9488],
        [ 129,  228,  147,  134],
        [2154, 2210, 1972, 2032],
        [   0,    0,    0,    0],
        [3556, 3362, 3405, 3479],
        [2892, 3505, 2917, 2854],
        [1292, 1408, 1288, 1276],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([2051], device='cuda:0') tensor([1273], device='cuda:0')
valid classification score:  tensor([0.2594], device='cuda:0')



Epoch: 31 | Epoch Time: 0m 19s
	Train Loss: 0.302 | Train Acc: 90.27%
	 Val. Loss: 0.589 |  Val. Acc: 85.20%
train metrics R, P, F1, F2
tensor([[9584, 9471, 9521, 9557],
        [ 125,  251,  147,  132],
        [2131, 2336, 2040, 2044],
        [   0,    0,    0,    0],
        [3341, 3444, 3343, 3330],
        [2698, 3469, 2751, 2671],
        [1532, 1373, 1398, 1459],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([772], device='cuda:0') tensor([413], device='cuda:0')
valid classification score:  tensor([0.1151], device='cuda:0')



Epoch: 32 | Epoch Time: 0m 19s
	Train Loss: 0.292 | Train Acc: 90.37%
	 Val. Loss: 0.396 |  Val. Acc: 89.44%
train metrics R, P, F1, F2
tensor([[9509, 9527, 9511, 9508],
        [ 151,  243,  164,  154],
        [2062, 2362, 2034, 2015],
        [   0,    0,    0,    0],
        [3519, 3411, 3423, 3469],
        [3086, 3678, 3149, 3068],
        [1440, 1453, 1409, 1419],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([2033], device='cuda:0') tensor([1352], device='cuda:0')
valid classification score:  tensor([0.2440], device='cuda:0')



Epoch: 33 | Epoch Time: 0m 19s
	Train Loss: 0.298 | Train Acc: 90.16%
	 Val. Loss: 0.375 |  Val. Acc: 90.40%
train metrics R, P, F1, F2
tensor([[9525, 9486, 9496, 9511],
        [ 130,  211,  141,  132],
        [2657, 2154, 2200, 2385],
        [   0,    0,    0,    0],
        [3440, 3470, 3385, 3401],
        [2777, 3482, 2875, 2777],
        [1223, 1355, 1200, 1197],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([1909], device='cuda:0') tensor([1188], device='cuda:0')
valid classification score:  tensor([0.2553], device='cuda:0')



Epoch: 34 | Epoch Time: 0m 19s
	Train Loss: 0.291 | Train Acc: 90.20%
	 Val. Loss: 0.306 |  Val. Acc: 90.97%
train metrics R, P, F1, F2
tensor([[9513, 9482, 9489, 9502],
        [  82,  162,   99,   88],
        [1781, 2368, 1902, 1806],
        [   0,    0,    0,    0],
        [3457, 3451, 3396, 3418],
        [3117, 3592, 3041, 3036],
        [1501, 1350, 1328, 1400],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([2431], device='cuda:0') tensor([1592], device='cuda:0')
valid classification score:  tensor([0.3054], device='cuda:0')



Epoch: 35 | Epoch Time: 0m 19s
	Train Loss: 0.282 | Train Acc: 90.64%
	 Val. Loss: 0.329 |  Val. Acc: 91.08%
train metrics R, P, F1, F2
tensor([[9474, 9562, 9511, 9487],
        [ 212,  312,  222,  213],
        [2165, 2386, 2144, 2127],
        [   0,    0,    0,    0],
        [3654, 3373, 3453, 3557],
        [3299, 3922, 3363, 3284],
        [1573, 1403, 1448, 1509],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([2677], device='cuda:0') tensor([1774], device='cuda:0')
valid classification score:  tensor([0.3363], device='cuda:0')



Epoch: 36 | Epoch Time: 0m 19s
	Train Loss: 0.286 | Train Acc: 90.43%
	 Val. Loss: 0.377 |  Val. Acc: 91.87%
train metrics R, P, F1, F2
tensor([[9519, 9496, 9497, 9507],
        [ 136,  269,  156,  141],
        [2274, 2500, 2237, 2224],
        [   0,    0,    0,    0],
        [3548, 3429, 3413, 3470],
        [3294, 3856, 3358, 3281],
        [1476, 1457, 1404, 1429],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([2507], device='cuda:0') tensor([1649], device='cuda:0')
valid classification score:  tensor([0.2940], device='cuda:0')



Epoch: 37 | Epoch Time: 0m 19s
	Train Loss: 0.265 | Train Acc: 90.96%
	 Val. Loss: 0.364 |  Val. Acc: 92.21%
train metrics R, P, F1, F2
tensor([[9584, 9493, 9532, 9561],
        [ 177,  293,  198,  182],
        [2502, 2421, 2328, 2393],
        [   0,    0,    0,    0],
        [3433, 3592, 3466, 3435],
        [3374, 3930, 3420, 3353],
        [1524, 1442, 1443, 1480],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([2685], device='cuda:0') tensor([1806], device='cuda:0')
valid classification score:  tensor([0.3076], device='cuda:0')



Epoch: 38 | Epoch Time: 0m 19s
	Train Loss: 0.266 | Train Acc: 91.17%
	 Val. Loss: 0.325 |  Val. Acc: 91.36%
train metrics R, P, F1, F2
tensor([[9499, 9574, 9531, 9510],
        [ 223,  379,  257,  233],
        [2285, 2400, 2220, 2229],
        [   0,    0,    0,    0],
        [3713, 3435, 3536, 3630],
        [3596, 3913, 3544, 3533],
        [1471, 1509, 1452, 1452],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([2742], device='cuda:0') tensor([1848], device='cuda:0')
valid classification score:  tensor([0.3353], device='cuda:0')



Epoch: 39 | Epoch Time: 0m 19s
	Train Loss: 0.330 | Train Acc: 89.48%
	 Val. Loss: 0.317 |  Val. Acc: 91.56%
train metrics R, P, F1, F2
tensor([[9536, 9458, 9483, 9511],
        [ 133,  254,  151,  137],
        [2406, 2402, 2200, 2267],
        [   0,    0,    0,    0],
        [3252, 3568, 3260, 3236],
        [2911, 3622, 3002, 2903],
        [1134, 1011, 1009, 1062],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([2784], device='cuda:0') tensor([1870], device='cuda:0')
valid classification score:  tensor([0.3125], device='cuda:0')



Epoch: 40 | Epoch Time: 0m 19s
	Train Loss: 0.324 | Train Acc: 89.98%
	 Val. Loss: 0.452 |  Val. Acc: 91.22%
train metrics R, P, F1, F2
tensor([[9564, 9449, 9494, 9533],
        [  73,  142,   83,   76],
        [1766, 2335, 1853, 1772],
        [   0,    0,    0,    0],
        [3432, 3454, 3385, 3399],
        [2587, 3454, 2659, 2567],
        [1404, 1322, 1307, 1349],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([2090], device='cuda:0') tensor([1353], device='cuda:0')
valid classification score:  tensor([0.2276], device='cuda:0')



Epoch: 41 | Epoch Time: 0m 19s
	Train Loss: 0.283 | Train Acc: 90.31%
	 Val. Loss: 0.327 |  Val. Acc: 91.16%
train metrics R, P, F1, F2
tensor([[9493, 9528, 9501, 9494],
        [  84,  214,  110,   92],
        [2344, 2260, 2106, 2193],
        [   0,    0,    0,    0],
        [3530, 3448, 3433, 3477],
        [3184, 3593, 3115, 3102],
        [1395, 1467, 1386, 1382],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([2532], device='cuda:0') tensor([1703], device='cuda:0')
valid classification score:  tensor([0.3152], device='cuda:0')



Epoch: 42 | Epoch Time: 0m 19s
	Train Loss: 0.264 | Train Acc: 91.02%
	 Val. Loss: 0.317 |  Val. Acc: 91.47%
train metrics R, P, F1, F2
tensor([[9563, 9515, 9533, 9549],
        [ 121,  234,  140,  127],
        [2592, 2489, 2417, 2481],
        [   0,    0,    0,    0],
        [3497, 3556, 3482, 3481],
        [3176, 4047, 3373, 3218],
        [1698, 1303, 1442, 1571],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([2452], device='cuda:0') tensor([1644], device='cuda:0')
valid classification score:  tensor([0.3057], device='cuda:0')



Epoch: 43 | Epoch Time: 0m 19s
	Train Loss: 0.252 | Train Acc: 91.11%
	 Val. Loss: 0.341 |  Val. Acc: 91.80%
train metrics R, P, F1, F2
tensor([[9522, 9550, 9530, 9524],
        [ 252,  408,  275,  257],
        [2562, 2510, 2427, 2474],
        [   0,    0,    0,    0],
        [3578, 3553, 3532, 3551],
        [3720, 3898, 3595, 3623],
        [1371, 1533, 1399, 1373],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([2902], device='cuda:0') tensor([1957], device='cuda:0')
valid classification score:  tensor([0.3437], device='cuda:0')



Epoch: 44 | Epoch Time: 0m 19s
	Train Loss: 0.261 | Train Acc: 91.13%
	 Val. Loss: 0.316 |  Val. Acc: 91.36%
train metrics R, P, F1, F2
tensor([[9569, 9526, 9541, 9556],
        [ 310,  483,  335,  315],
        [2354, 2504, 2297, 2302],
        [   0,    0,    0,    0],
        [3454, 3615, 3495, 3463],
        [3625, 4033, 3614, 3579],
        [1457, 1505, 1442, 1443],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([2417], device='cuda:0') tensor([1596], device='cuda:0')
valid classification score:  tensor([0.3064], device='cuda:0')



Epoch: 45 | Epoch Time: 0m 19s
	Train Loss: 0.270 | Train Acc: 90.97%
	 Val. Loss: 0.328 |  Val. Acc: 90.31%
train metrics R, P, F1, F2
tensor([[9551, 9527, 9532, 9542],
        [ 266,  432,  298,  274],
        [2427, 2457, 2329, 2356],
        [   0,    0,    0,    0],
        [3529, 3487, 3447, 3481],
        [3329, 3902, 3358, 3289],
        [1209, 1327, 1224, 1209],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([2979], device='cuda:0') tensor([2049], device='cuda:0')
valid classification score:  tensor([0.3709], device='cuda:0')



Epoch: 46 | Epoch Time: 0m 19s
	Train Loss: 0.260 | Train Acc: 90.89%
	 Val. Loss: 0.337 |  Val. Acc: 90.59%
train metrics R, P, F1, F2
tensor([[9517, 9549, 9526, 9519],
        [ 131,  315,  168,  142],
        [2300, 2510, 2268, 2254],
        [   0,    0,    0,    0],
        [3605, 3487, 3505, 3554],
        [3675, 3944, 3588, 3588],
        [1531, 1397, 1393, 1451],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([2383], device='cuda:0') tensor([1555], device='cuda:0')
valid classification score:  tensor([0.2989], device='cuda:0')



Epoch: 47 | Epoch Time: 0m 19s
	Train Loss: 0.253 | Train Acc: 91.09%
	 Val. Loss: 0.366 |  Val. Acc: 89.99%
train metrics R, P, F1, F2
tensor([[9504, 9578, 9535, 9515],
        [ 220,  363,  247,  227],
        [2294, 2347, 2191, 2217],
        [   0,    0,    0,    0],
        [3631, 3510, 3531, 3580],
        [3665, 3874, 3541, 3563],
        [1473, 1497, 1449, 1454],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([2140], device='cuda:0') tensor([1399], device='cuda:0')
valid classification score:  tensor([0.2758], device='cuda:0')



Epoch: 48 | Epoch Time: 0m 19s
	Train Loss: 0.240 | Train Acc: 91.44%
	 Val. Loss: 0.373 |  Val. Acc: 91.44%
train metrics R, P, F1, F2
tensor([[9576, 9538, 9552, 9566],
        [ 393,  565,  412,  394],
        [2649, 2550, 2485, 2549],
        [   0,    0,    0,    0],
        [3570, 3570, 3538, 3549],
        [3368, 4108, 3471, 3366],
        [1656, 1416, 1490, 1572],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([2574], device='cuda:0') tensor([1710], device='cuda:0')
valid classification score:  tensor([0.3054], device='cuda:0')



Epoch: 49 | Epoch Time: 0m 19s
	Train Loss: 0.249 | Train Acc: 91.35%
	 Val. Loss: 0.412 |  Val. Acc: 91.64%
train metrics R, P, F1, F2
tensor([[9534, 9556, 9539, 9534],
        [ 432,  601,  460,  437],
        [2324, 2511, 2302, 2290],
        [   0,    0,    0,    0],
        [3643, 3519, 3545, 3594],
        [3669, 3973, 3579, 3582],
        [1533, 1445, 1425, 1474],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([2678], device='cuda:0') tensor([1795], device='cuda:0')
valid classification score:  tensor([0.3150], device='cuda:0')



Epoch: 50 | Epoch Time: 0m 19s
	Train Loss: 0.271 | Train Acc: 91.07%
	 Val. Loss: 0.387 |  Val. Acc: 91.47%
train metrics R, P, F1, F2
tensor([[9545, 9528, 9529, 9537],
        [ 184,  379,  222,  195],
        [2319, 2525, 2281, 2274],
        [   0,    0,    0,    0],
        [3588, 3507, 3500, 3541],
        [3341, 3941, 3420, 3335],
        [1525, 1363, 1391, 1452],
        [   0,    0,    0,    0]])
valid metrics DICE2, AJI
tensor([2206], device='cuda:0') tensor([1433], device='cuda:0')
valid classification score:  tensor([0.2719], device='cuda:0')


In [ ]:
N_EPOCHS = 50

best_valid_loss = float('inf')

for epoch in range(N_EPOCHS):

    start_time = time.time()

    train_loss, train_acc, train_stats = train(model, training_generator, optimizer, criterion)
    valid_loss, valid_acc, valid_stats = evaluate(model, validation_generator, criterion)

    end_time = time.time()

    epoch_mins, epoch_secs = epoch_time(start_time, end_time)

    if valid_loss < best_valid_loss:
        best_valid_loss = valid_loss
        torch.save(model.state_dict(), drivePath + 'unetplusplus.pt')

    print(f'Epoch: {epoch+1:02} | Epoch Time: {epoch_mins}m {epoch_secs}s')
    print(f'\tTrain Loss: {train_loss:.3f} | Train Acc: {train_acc*100:.2f}%')
    print(f'\t Val. Loss: {valid_loss:.3f} |  Val. Acc: {valid_acc*100:.2f}%')
    print('train metrics R, P, F1, F2')
    print((train_stats * 1e4).long())
    print('valid metrics R, P, F1, F2')
    print((valid_stats * 1e4).long())

In [ ]:
model.load_state_dict(torch.load(drivePath + 'unetplusplus.pt'))

test_loss, test_acc, test_stats = evaluate(model, test_generator, criterion, demo = True)

print(f'Test Loss: {test_loss:.3f} | Test Acc: {test_acc*100:.2f}%')
print('test metrics R, P, F1, F2')
print((test_stats * 1e4).long())